name:                goi
version:             1.0.0
github:              "jasonstolaruk/goi"
license:             BSD3
author:              "Jason P. Stolaruk"
maintainer:          "jasonstolaruk@gmail.com"
copyright:           "2022 Jason P. Stolaruk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jasonstolaruk/goi#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  goi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - directory
    - goi
    - mtl
    - sqlite-simple
    - text
    when:
    - condition: false
      other-modules: Paths_goi

tests:
  goi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - goi
